# Pull base image for python
FROM python:3.8-slim

# Set the working directory in the image
WORKDIR /app

# Copy the current directory content at the app
COPY . /app

# Run the application
CMD [ "python", "app.py" ] 